In [94]:
import numpy as np

# 1. 5개의 데이터(행), 3개의 클래스(열)가 있는 가상의 점수 행렬 (N=5, C=3)
scores = np.array([
    [10, 20, 30],  # 0번 데이터 점수
    [40, 50, 60],  # 1번 데이터 점수
    [70, 80, 90],  # 2번 데이터 점수
    [11, 22, 33],  # 3번 데이터 점수
    [44, 55, 66]   # 4번 데이터 점수
])

# 2. 각 데이터의 실제 정답 클래스 (y)
y = np.array([2, 0, 1, 1, 2]) # 0번은 2번클래스, 1번은 0번클래스... 가 정답

# 3. 정답 위치의 점수만 쏙 뽑아오기 (Advanced Indexing)
# np.arange(5)는 [0, 1, 2, 3, 4]를 생성합니다.
correct_scores = scores[np.arange(5), y]

print("정답 점수들:", correct_scores) 
# 예상 출력: [30, 40, 80, 22, 66]

정답 점수들: [30 40 80 22 66]


In [95]:
x = np.zeros((3 ,5))
y = np.zeros_like(x)
print(x, y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [96]:
x_train = np.zeros((50000, 32, 32, 3))
y_train = np.zeros((50000, ))
x_test = np.zeros((10000, 32, 32, 3))
y_test = np.zeros((10000, ))
# 위 코드는 원래 CIFAR-10을 실행하면 자동으로 됨

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(50000, 32, 32, 3)
(50000,)
(10000, 32, 32, 3)
(10000,)


In [97]:
# set the size of each data
num_training = 49000
num_validation = 1000
num_test = 1000
num_dev = 500

# change correct idx
mask = range(num_training, num_training + num_validation)
x_val = x_train[mask]
y_val = y_train[mask]

mask = range(num_training)
x_train = x_train[mask]
y_train = y_train[mask]

mask = np.random.choice(num_training, num_dev, replace=False)
x_dev = x_train[mask]
y_dev = y_train[mask]

mask = range(num_test)
x_test = x_test[mask]
y_test = y_test[mask]

print(x_train.shape)
print(y_train.shape)
print(x_val.shape)
print(y_val.shape)
print(x_dev.shape)
print(y_dev.shape)
print(x_test.shape)
print(y_test.shape)

(49000, 32, 32, 3)
(49000,)
(1000, 32, 32, 3)
(1000,)
(500, 32, 32, 3)
(500,)
(1000, 32, 32, 3)
(1000,)


In [98]:
x_train = np.reshape(x_train, (num_training, -1))
x_val = np.reshape(x_val, (num_validation, -1))
x_dev = np.reshape(x_dev, (num_dev, -1))
x_test = np.reshape(x_test, (num_test, -1))

print(x_train.shape)
print(x_val.shape)
print(x_dev.shape)
print(x_test.shape)

(49000, 3072)
(1000, 3072)
(500, 3072)
(1000, 3072)


In [99]:
# 각 데이터에 bias 항 추가 (weight만 신경쓰면 되도록)
x_train = np.hstack([x_train, np.ones((x_train.shape[0], 1))])
x_val = np.hstack([x_val, np.ones((x_val.shape[0], 1))])
x_test = np.hstack([x_test, np.ones((x_test.shape[0], 1))])
x_dev = np.hstack([x_dev, np.ones((x_dev.shape[0], 1))])

print(x_train.shape, x_val.shape, x_test.shape, x_dev.shape)

(49000, 3073) (1000, 3073) (1000, 3073) (500, 3073)


In [100]:
# weight & softmax
%load_ext autoreload
%autoreload 2
from softmax import softmax_loss_vectorized

W = np.random.randn(3073, 10) * 0.0001

loss, grad = softmax_loss_vectorized(W, x_dev, y_dev, 0.000005)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
hello


TypeError: cannot unpack non-iterable NoneType object